version: '3.8'
# Run automatically on startup
services:
  app:
    build: 
      context: .
      target: php
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data: ~
  # app_data: ~