name: CD Test

on:
  workflow_run:
    workflows: ["CI Test"]
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to VPS
      run: ssh root@46.250.239.158 "echo 'Connected to VPS!'" 

    - name: Go into project directory and pull latest changes
      run: cd /var/www/website103 && git pull origin master

    - name: Build and restart Docker containers
      run: |
        cd /var/www/website103
        docker compose build
        docker compose up -d --wait || true

    - name: migrate database
      run: docker compose exec app php artisan migrate --force

    - name: Clear or Optimize Cache
      run: docker compose exec app php artisan optimize:clear
      
    - name: Clear permission cache
      run: docker compose exec app php artisan permission:cache-reset
